export const styles = {
  root: {
    minHeight: "100vh",
    background: "linear-gradient(135deg, #e8f5e9 0%, #f1f8e9 50%, #e0f7fa 100%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "20px",
    position: "relative",
    overflow: "hidden",
  },
  bgCircle1: {
    position: "fixed",
    width: 400,
    height: 400,
    borderRadius: "50%",
    background: "rgba(76, 175, 80, 0.08)",
    top: -100,
    right: -100,
    pointerEvents: "none",
  },
  bgCircle2: {
    position: "fixed",
    width: 300,
    height: 300,
    borderRadius: "50%",
    background: "rgba(0, 188, 212, 0.08)",
    bottom: -80,
    left: -80,
    pointerEvents: "none",
  },
  container: {
    width: "100%",
    maxWidth: 720,
    background: "rgba(255,255,255,0.85)",
    backdropFilter: "blur(20px)",
    borderRadius: 24,
    boxShadow: "0 20px 60px rgba(0,0,0,0.1)",
    display: "flex",
    flexDirection: "column",
    height: "90vh",
    overflow: "hidden",
    border: "1px solid rgba(255,255,255,0.9)",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "20px 24px",
    borderBottom: "1px solid rgba(0,0,0,0.06)",
    background: "rgba(255,255,255,0.9)",
  },
  headerIcon: { fontSize: 36 },
  headerTitle: {
    fontSize: 20,
    fontWeight: 700,
    color: "#1b5e20",
    letterSpacing: "-0.5px",
  },
  headerSub: { fontSize: 12, color: "#78909c", marginTop: 2 },
  statusBadge: {
    marginLeft: "auto",
    display: "flex",
    alignItems: "center",
    gap: 6,
    background: "#e8f5e9",
    color: "#2e7d32",
    fontSize: 12,
    fontWeight: 600,
    padding: "4px 12px",
    borderRadius: 20,
  },
  statusDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#4caf50",
    display: "inline-block",
  },
  messages: {
    flex: 1,
    overflowY: "auto",
    padding: "20px 24px",
    display: "flex",
    flexDirection: "column",
    gap: 16,
  },
  messageRow: { display: "flex", alignItems: "flex-end", gap: 10 },
  botAvatar: { fontSize: 28, flexShrink: 0 },
  bubble: { maxWidth: "75%", padding: "12px 16px", borderRadius: 18, lineHeight: 1.6 },
  botBubble: {
    background: "white",
    boxShadow: "0 2px 12px rgba(0,0,0,0.08)",
    borderBottomLeftRadius: 4,
  },
  userBubble: {
    background: "linear-gradient(135deg, #2e7d32, #43a047)",
    borderBottomRightRadius: 4,
  },
  bubbleText: { fontSize: 14, whiteSpace: "pre-wrap" },
  sources: { marginTop: 10, paddingTop: 10, borderTop: "1px solid rgba(0,0,0,0.06)" },
  sourcesTitle: { fontSize: 11, fontWeight: 600, color: "#78909c", marginBottom: 4 },
  sourceItem: { fontSize: 11, color: "#90a4ae", marginTop: 2 },
  dots: { display: "flex", gap: 5, padding: "4px 0" },
  dot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#4caf50",
    display: "inline-block",
    animation: "bounce 0.8s infinite",
  },
  suggestions: { display: "flex", flexWrap: "wrap", gap: 8, padding: "0 24px 16px" },
  suggestionBtn: {
    background: "white",
    border: "1px solid #c8e6c9",
    color: "#2e7d32",
    borderRadius: 20,
    padding: "6px 14px",
    fontSize: 12,
    cursor: "pointer",
    fontFamily: "inherit",
  },
  inputRow: {
    display: "flex",
    gap: 10,
    padding: "16px 24px",
    borderTop: "1px solid rgba(0,0,0,0.06)",
    background: "rgba(255,255,255,0.9)",
  },
  input: {
    flex: 1,
    border: "1px solid #e0e0e0",
    borderRadius: 12,
    padding: "12px 16px",
    fontSize: 14,
    fontFamily: "inherit",
    outline: "none",
    background: "#fafafa",
    color: "#333",
  },
  sendBtn: {
    background: "linear-gradient(135deg, #2e7d32, #43a047)",
    color: "white",
    border: "none",
    borderRadius: 12,
    padding: "12px 20px",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
    fontFamily: "inherit",
  },
};